# Docker Compose configuration for Django + SQLite
version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - migrate
  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    env_file:
      - .env
