# Generated by Django 5.2.4 on 2025-08-06 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ders Adı")),
                (
                    "icon",
                    models.CharField(default="📚", max_length=10, verbose_name="İkon"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
            ],
            options={
                "verbose_name": "Ders",
                "verbose_name_plural": "Dersler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Oturum Başlığı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif Oturum"),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(default=0, verbose_name="Mesaj Sayısı"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Oturumu",
                "verbose_name_plural": "Chat Oturumları",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fastapi_request_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="FastAPI Request ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Video Başlığı"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Video Açıklaması"),
                ),
                (
                    "video_style",
                    models.CharField(
                        choices=[
                            ("animated", "Animasyonlu"),
                            ("whiteboard", "Tahta Üzerinde"),
                            ("modern", "Modern UI"),
                        ],
                        default="animated",
                        max_length=20,
                    ),
                ),
                (
                    "duration_preference",
                    models.CharField(
                        choices=[
                            ("short", "Kısa (1-2 dakika)"),
                            ("medium", "Orta (3-5 dakika)"),
                            ("long", "Uzun (6-10 dakika)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "speech_speed",
                    models.CharField(
                        choices=[
                            ("slow", "Yavaş"),
                            ("normal", "Normal"),
                            ("fast", "Hızlı"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "has_background_music",
                    models.BooleanField(default=True, verbose_name="Arka Plan Müziği"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Oluşturuluyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="Video URL"),
                ),
                (
                    "direct_video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Direkt Video URL"
                    ),
                ),
                (
                    "static_video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Statik Video URL"
                    ),
                ),
                (
                    "file_size_mb",
                    models.FloatField(default=0, verbose_name="Dosya Boyutu (MB)"),
                ),
                (
                    "actual_duration_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Gerçek Süre (saniye)"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Görüntülenme"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="İndirme"),
                ),
                (
                    "chat_messages_json",
                    models.TextField(verbose_name="Chat Mesajları JSON"),
                ),
                (
                    "message_up_to_id",
                    models.CharField(max_length=200, verbose_name="Hangi Mesaja Kadar"),
                ),
                ("generation_started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_status_check", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="core.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Videosu",
                "verbose_name_plural": "Chat Videoları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "Mesaj"),
                            ("solution", "Çözüm"),
                            ("system", "Sistem"),
                            ("achievement", "Başarı"),
                            ("video", "Video"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dark_mode", models.BooleanField(default=False)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sound_enabled", models.BooleanField(default=True)),
                ("auto_save", models.BooleanField(default=True)),
                ("compact_view", models.BooleanField(default=False)),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Türkçe"), ("en", "English")],
                        default="tr",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ayar",
                "verbose_name_plural": "Ayarlar",
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("step_by_step", models.TextField(verbose_name="Adım Adım Çözüm")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Virgülle ayırın", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Görüntülenme"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="Beğeni"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_solutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Çözüm",
                "verbose_name_plural": "Çözümler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Konu Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Konu Açıklaması")),
                ("content", models.TextField(verbose_name="Konu İçeriği")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Başlangıç"),
                            ("intermediate", "Orta"),
                            ("advanced", "İleri"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Virgülle ayırın", max_length=500
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Tahmini Süre (dakika)"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Görüntülenme"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu İçeriği",
                "verbose_name_plural": "Konu İçerikleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EducationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Eğitim Başlığı"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Eğitim Açıklaması"),
                ),
                (
                    "education_type",
                    models.CharField(
                        choices=[
                            ("text", "Metin Eğitimi"),
                            ("audio", "Sesli Eğitim"),
                            ("video", "Videolu Eğitim"),
                            ("interactive", "İnteraktif Eğitim"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "use_internet_search",
                    models.BooleanField(
                        default=False, verbose_name="İnternet Araması Kullan"
                    ),
                ),
                (
                    "include_materials",
                    models.BooleanField(
                        default=True, verbose_name="Materyalleri Dahil Et"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Türkçe"), ("en", "English")],
                        default="tr",
                        max_length=10,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Tahmini Süre (dakika)"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Oluşturulan İçerik"),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="education_audio/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="education_videos/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="education_thumbnails/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Oluşturuluyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Görüntülenme"),
                ),
                (
                    "completion_rate",
                    models.FloatField(default=0.0, verbose_name="Tamamlanma Oranı (%)"),
                ),
                ("generation_started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_sessions",
                        to="core.topiccontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eğitim Oturumu",
                "verbose_name_plural": "Eğitim Oturumları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Materyal Başlığı"),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Doküman"),
                            ("doc", "Word Doküman"),
                            ("video", "Video"),
                            ("audio", "Ses Dosyası"),
                            ("image", "Görsel"),
                            ("link", "Dış Bağlantı"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="topic_materials/"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Dış Bağlantı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dosya Boyutu (bytes)"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="İndirme Sayısı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.topiccontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu Materyali",
                "verbose_name_plural": "Konu Materyalleri",
                "ordering": ["material_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="UserSolutionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_time", models.DurationField(blank=True, null=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.solution"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Çözüm İlerlemesi",
                "verbose_name_plural": "Kullanıcı Çözüm İlerlemeleri",
                "unique_together": {("user", "solution")},
            },
        ),
    ]
