# Generated by Django 5.2.4 on 2025-07-27 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ChatVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Video Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Video Açıklaması')),
                ('video_style', models.CharField(choices=[('animated', 'Animasyonlu'), ('whiteboard', 'Tahta Üzerinde'), ('modern', 'Modern UI')], default='animated', max_length=20)),
                ('duration_preference', models.CharField(choices=[('short', 'Kısa (1-2 dakika)'), ('medium', 'Orta (3-5 dakika)'), ('long', 'Uzun (6-10 dakika)')], default='medium', max_length=10)),
                ('speech_speed', models.CharField(choices=[('slow', 'Yavaş'), ('normal', 'Normal'), ('fast', 'Hızlı')], default='normal', max_length=10)),
                ('has_background_music', models.BooleanField(default=True, verbose_name='Arka Plan Müziği')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='chat_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chat_video_thumbnails/')),
                ('actual_duration', models.DurationField(blank=True, null=True, verbose_name='Gerçek Süre')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dosya Boyutu (bytes)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='İndirme')),
                ('status', models.CharField(choices=[('generating', 'Oluşturuluyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='generating', max_length=20)),
                ('chat_messages_count', models.PositiveIntegerField(default=0, verbose_name='İşlenen Mesaj Sayısı')),
                ('generation_started_at', models.DateTimeField(auto_now_add=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Videosu',
                'verbose_name_plural': 'Chat Videoları',
                'ordering': ['-created_at'],
            },
        ),
    ]
