# Generated by Django 5.2.4 on 2025-07-29 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_chatsession_id_chatvideo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Konu Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Konu Açıklaması")),
                ("content", models.TextField(verbose_name="Konu İçeriği")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Başlangıç"),
                            ("intermediate", "Orta"),
                            ("advanced", "İleri"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Virgülle ayırın", max_length=500
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Tahmini Süre (dakika)"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Görüntülenme"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu İçeriği",
                "verbose_name_plural": "Konu İçerikleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EducationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Eğitim Başlığı"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Eğitim Açıklaması"),
                ),
                (
                    "education_type",
                    models.CharField(
                        choices=[
                            ("text", "Metin Eğitimi"),
                            ("audio", "Sesli Eğitim"),
                            ("video", "Videolu Eğitim"),
                            ("interactive", "İnteraktif Eğitim"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "use_internet_search",
                    models.BooleanField(
                        default=False, verbose_name="İnternet Araması Kullan"
                    ),
                ),
                (
                    "include_materials",
                    models.BooleanField(
                        default=True, verbose_name="Materyalleri Dahil Et"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("tr", "Türkçe"), ("en", "English")],
                        default="tr",
                        max_length=10,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Tahmini Süre (dakika)"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Oluşturulan İçerik"),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="education_audio/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="education_videos/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="education_thumbnails/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Oluşturuluyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Görüntülenme"),
                ),
                (
                    "completion_rate",
                    models.FloatField(default=0.0, verbose_name="Tamamlanma Oranı (%)"),
                ),
                ("generation_started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_sessions",
                        to="core.topiccontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eğitim Oturumu",
                "verbose_name_plural": "Eğitim Oturumları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Materyal Başlığı"),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Doküman"),
                            ("doc", "Word Doküman"),
                            ("video", "Video"),
                            ("audio", "Ses Dosyası"),
                            ("image", "Görsel"),
                            ("link", "Dış Bağlantı"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="topic_materials/"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Dış Bağlantı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dosya Boyutu (bytes)"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="İndirme Sayısı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="core.topiccontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu Materyali",
                "verbose_name_plural": "Konu Materyalleri",
                "ordering": ["material_type", "title"],
            },
        ),
    ]
