# Generated by Django 5.2.4 on 2025-08-06 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Maya", max_length=100)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("realistic", "Gerçekçi"),
                            ("cartoon", "Çizgi Film"),
                            ("anime", "Anime"),
                            ("3d", "3D"),
                        ],
                        default="realistic",
                        max_length=20,
                    ),
                ),
                (
                    "hair_color",
                    models.CharField(
                        choices=[
                            ("black", "Siyah"),
                            ("brown", "Kahverengi"),
                            ("blonde", "Sarışın"),
                            ("red", "Kızıl"),
                            ("gray", "Gri"),
                            ("other", "Diğer"),
                        ],
                        default="brown",
                        max_length=20,
                    ),
                ),
                (
                    "eye_color",
                    models.CharField(
                        choices=[
                            ("brown", "Kahverengi"),
                            ("blue", "Mavi"),
                            ("green", "Yeşil"),
                            ("hazel", "Ela"),
                            ("gray", "Gri"),
                            ("amber", "Kehribar"),
                        ],
                        default="brown",
                        max_length=20,
                    ),
                ),
                ("personality", models.TextField(blank=True, max_length=1000)),
                (
                    "avatar_image",
                    models.ImageField(blank=True, null=True, upload_to="ai_avatars/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_avatar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Avatar",
                "verbose_name_plural": "AI Avatarlar",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Metin"),
                            ("file", "Dosya"),
                            ("image", "Resim"),
                            ("audio", "Ses"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "file_attachment",
                    models.FileField(blank=True, null=True, upload_to="chat_files/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_bot_response", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Mesajı",
                "verbose_name_plural": "Chat Mesajları",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, default="avatars/default.jpg", upload_to="avatars/"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "Kadın"),
                            ("male", "Erkek"),
                            ("other", "Diğer"),
                        ],
                        default="female",
                        max_length=10,
                    ),
                ),
                (
                    "membership",
                    models.CharField(
                        choices=[
                            ("basic", "Temel Üye"),
                            ("premium", "Premium Üye"),
                            ("vip", "VIP Üye"),
                        ],
                        default="basic",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("notification_enabled", models.BooleanField(default=True)),
                ("dark_mode", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
    ]
